version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8888:8888"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8887:8887"
