name: Deploy Backend Docs

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Javadoc
        run: |
          tmp=$(mktemp -d) && \
          cd backend && \
          make javadoc && \
          mv docs "$tmp" && \
          mkdir -p docs/javadoc && \
          mv $tmp/docs/* docs/javadoc

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./backend/docs/javadoc
