name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer@latest | node

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: presentation/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm --prefix presentation/ install --frozen-lockfile

      - name: Build Docs
        run: make docs DOCS_BASE_PATH="/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
